# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='howtodeal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='howtodeliver',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
