# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170219_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
