# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
