# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_url_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='now_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
