# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_now_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='now_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='url',
            name='product_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
