# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20170729_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='howtodeal',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='howtodeliver',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='info',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='photo',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_info',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='cart',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
